version: "3.5"

services:

   orange-app:
      image: leovs09/orange-app:0.1.0
      container_name: orange-app
      ports:
         - 8080:8080
      volumes:
         - .:/ws/.

   orange-database:
      image: leovs09/orange-database:0.1.0
      container_name: orange-database
      ports:
         - 8765:8765
      env_file:
         - .env-list
      depends_on:
         - db
      links:
         - db

   db:
      image: postgres:11
      container_name: postgres
      volumes:
         - ./postgres-data:/var/lib/postgresql/data
      ports:
         - 5432:5432
