// UI
export const SET_PLATFORM = 'SET_PLATFORM';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SET_TEXT_PAGE = 'SET_TEXT_PAGE';
export const SET_STANDARD_PAGE = 'SET_STANDARD_PAGE';
export const SET_SIGN_IN_PAGE = 'SET_SIGN_IN_PAGE';
export const SET_SIGN_UP_PAGE = 'SET_SIGN_UP_PAGE';

// PROFILE
export const SETUP_USER_PROFILE = 'SETUP_USER_PROFILE';
export const LOGIN_TO_PROFILE = 'LOGIN_TO_PROFILE';
export const REGISTER_PROFILE = 'REGISTER_PROFILE';
export const LOGOUT_FROM_PROFILE = 'LOGOUT_FROM_PROFILE';

// PROBLEMS
export const SETUP_PROBLEMS = 'SETUP_PROBLEMS';
export const ADD_PROBLEM = 'ADD_PROBLEM';
export const UPLOAD_CODE = 'UPLOAD_CODE';
export const SET_CURRRENT_PROBLEM = 'SET_CURRRENT_PROBLEM';
export const SYNC_PROBLEMS = 'SYNC_PROBLEMS';
