// UI
export const SET_PLATFORM = 'SET_PLATFORM';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

// PROFILE
export const SETUP_USER_PROFILE = 'SETUP_USER_PROFILE';

// PROBLEMS
export const SETUP_OPEN_PROBLEMS = 'SETUP_OPEN_PROBLEMS';
export const ADD_OPEN_PROBLEM = 'ADD_OPEN_PROBLEM';
