export const SETUP_USER_PROFILE = 'SETUP_USER_PROFILE'
export const LOGIN_TO_PROFILE = 'LOGIN_TO_PROFILE'
export const REGISTER_PROFILE = 'REGISTER_PROFILE'
export const LOGOUT_FROM_PROFILE = 'LOGOUT_FROM_PROFILE'
export const INIT_PROFILE = 'INIT_PROFILE'

export const INITIALISE_PROFILE_DATA = 'INITIALISE_PROFILE_DATA'
