export const SET_PROBLEMS = 'SET_PROBLEMS';

export const ADD_PARTIAL_READ_PROBLEM = 'ADD_PARTIAL_READ_PROBLEM';
export const ADD_FULL_READ_PROBLEM = 'ADD_FULL_READ_PROBLEM';
export const ADD_PROBLEM_FOR_CREATE = 'ADD_PROBLEM_FOR_CREATE';

export const SET_RESULT_OF_SOLUTION_RUN = 'SET_RESULT_OF_SOLUTION_RUN';
export const START_TESTING_SOLUTION = 'START_TESTING_SOLUTION';

export const ADD_TEST_FOR_CREATE = 'ADD_TEST_FOR_CREATE';
export const CREATE_TEST = 'CREATE_TEST'
export const EDIT_TEST = 'EDIT_TEST';
export const UPDATE_TEST = 'UPDATE_TEST';
export const SET_TEST_STATUS = 'SET_TEST_STATUS'

export const CREATE_PROBLEM = 'CREATE_PROBLEM'
export const UPDATE_PROBLEM = 'UPDATE_PROBLEM';
export const EDIT_PROBLEM = 'EDIT_PROBLEM';
export const SET_PROBLEM_STATUS = 'SET_PROBLEM_STATUS';

