export const SET_RESULT_OF_SOLUTION_RUN = 'SET_RESULT_OF_SOLUTION_RUN';
export const START_TESTING_SOLUTION = 'START_TESTING_SOLUTION';

export const SET_TESTS = 'SET_TESTS'
export const SET_OR_ADD_TEST = 'SET_OR_ADD_TEST'
export const DELETE_TEST = 'DELETE_TEST';
export const SET_BY_ID_TEST = 'SET_BY_ID_TEST';

export const ADD_PROBLEM_ERROR = 'ADD_PROBLEM_ERROR'
export const SET_PROBLEMS_FILTER = 'SET_PROBLEMS_FILTER';
