export const UI_SET_PLATFORM_REPRESENTATION = 'UI_SET_PLATFORM_REPRESENTATION';
export const UI_SET_SIDEBAR_VISIBLE_STATUS = 'UI_SET_SIDEBAR_VISIBLE_STATUS';
export const UI_SET_SIGN_IN_PAGE_STATUS = 'UI_SET_SIGN_IN_PAGE_STATUS';
export const SET_LOCALE = 'SET_LOCALE';
